### ISSUE TITLE
PID file issues

### ISSUE THREAD

**Issue by PAStheLoD** [vmware-archive/salt-api#85] opened 2013-05-28 14:51 UTC
Hello!

I'm testing 0.8.1, and while using the -d daemon mode and the --pid-file option, it seems that there are a few problems:
- sending SIGTERM to main salt-api process doesn't result in a complete salt-api shutdown
- the PID file remains after salt-api has shut itself down

So it's currently quite hard to use it as a proper "unix daemon".

**Comment by whiteinge** [comment] 2013-06-01 22:04
@PAStheLoD thanks for the report! Can you verify the above pull req fixes the issue?

**Comment by whiteinge** [comment] 2013-07-10 17:29
Closing. Please feel free to reopen if the issue isn't resolved.

**Closed as completed by whiteinge** 2013-07-10 17:29 UTC

**Comment by PAStheLoD** [comment] 2013-07-15 11:54
Hello! Thanks and sorry for lack of feedback. I'll report anything I encounter, when I'll get some time to further play with the Salt API.
